# imagen base
FROM python:3.7.0-alpine

# instalando dependencias
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# estableciendo carpeta de trabajo
WORKDIR /usr/src/app

# copiando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copiando entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copiar app
COPY . /usr/src/app

# ejecutar servidor
# CMD ["/usr/src/app/entrypoint.sh"]
CMD ["sh","-c","chmod 755 /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh"]
