# imagen base
FROM python:3.7.0-alpine

# estableciendo carpeta de trabajo
WORKDIR /usr/src/app

# copiando e instalando requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# copiar app
COPY . /usr/src/app

# ejecutar servidor
CMD python manage.py run -h 0.0.0.0
